excerpt_separator: ""
pygments: ""
url: http://nicomedinap.github.io
title: 
tagline: Interpretando luz de las estrellas
description: Fotómetro
paginate: 5
theme: jekyll-theme-cayman
highlighter: rouge
