excerpt_separator: ""
pygments: ""
url: http://nicomedinap.github.io
title: Fotómetro
tagline: A la física le falta código
description: Código y ciencia
paginate: 5
theme: jekyll-theme-cayman
highlighter: rouge
