excerpt_separator: ""
pygments: ""
url: http://nicomedinap.github.io
title: Fotómetro
tagline: Interpretando luz de las estrellas
description: "holi"
paginate: 10
theme: jekyll-theme-cayman
highlighter: rouge
