excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://nicomedinap.github.io
title: nicomedinap
tagline: A log of everyday life
description: Bash
paginate: 5
theme: jekyll-theme-cayman
